name: Release

on:
  push:
    tags:
      - 'release/v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bsky-one-click-block.zip
